# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "adcyberwatch-infra"
region = "ca-central-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "adcyberwatch-poc"
s3_prefix = "adcyberwatch-poc"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Environment: dev
[dev.global.parameters]
stack_name = "adcyberwatch-infra"
region = "ca-central-1"

[dev.build.parameters]
cached = true
parallel = true

[dev.validate.parameters]
lint = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
stack_name = "adcyberwatch-poc"
s3_prefix = "adcyberwatch-poc"
image_repositories = []

[dev.package.parameters]
resolve_s3 = true

[dev.sync.parameters]
watch = true

[dev.local_start_api.parameters]
warm_containers = "EAGER"

[dev.local_start_lambda.parameters]
warm_containers = "EAGER"
